CREATE TABLE PRODUCTS
(
   ID           INTEGER NOT NULL AUTO_INCREMENT,
   DESCRIPTION  VARCHAR(255),
   NAME         VARCHAR(255),
   PRIMARY KEY (ID)
);

CREATE TABLE DOCUMENT
(
   DOCUMENT_ID  INTEGER NOT NULL AUTO_INCREMENT,
   AMOUNT       INTEGER,
   CREATE_DATE  TIMESTAMP,
   DESCRIPTION  VARCHAR(255),
   OPERATION    VARCHAR(255),
   PRODUCT      INTEGER,
   PRIMARY KEY (DOCUMENT_ID),
   CONSTRAINT FK_DOCUMENT_1 FOREIGN KEY (PRODUCT)
  REFERENCES PRODUCTS (ID)
);

CREATE TABLE STORE
(
   PRODUCT_ID  INTEGER   NOT NULL AUTO_INCREMENT,
   "COUNT"     INTEGER,
   PRIMARY KEY (PRODUCT_ID)
);



